### ISSUE TITLE
PyPI package doesn't contain utils

### ISSUE THREAD

**Issue by michel-slm** [joaogbcravo/gocdapi#9]
The `utils` directory is not contained in the archive published on PyPI, resulting in an error when attempting to import gocdapi:

```
>>> import gocdapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/michel/.virtualenvs/gocd-slackbot/local/lib/python2.7/site-packages/gocdapi/__init__.py", line 34, in <module>
    from gocdapi import (
  File "/home/michel/.virtualenvs/gocd-slackbot/local/lib/python2.7/site-packages/gocdapi/admin.py", line 6, in <module>
    from gocdapi.utils.config_xml import ConfigXML
ImportError: No module named utils.config_xml
```

**Comment by joaogbcravo** [comment]
I guess it's fixed... Thanks for spot it!

Cheers
